stages: 
    - cml_run
    
cml:
    
    stage: cml_run
    image: frasermince/gym:latest
    artifacts:
      paths:
        - ./video/Pong-v0
        - ./lightning_logs
      expire_in: 1 week
    script:
        - pip install -r requirements.txt
        - dvc pull data --run-cache
        
        - python dqn/dqn.py test 1 100 200 true
        - cml-tensorboard-dev \
            --logdir /builds/frasermince/rl-papers/lightning_logs \
            --name "Go to tensorboard" \
            --md >> report.md

        - cml-send-comment report.md
