stages: 
    - cml_run
    
cml:
    stage: cml_run
    image: frasermince/gym:latest
    script:
        - pip install -r requirements.txt
        - cml-tensorboard-dev \
            --logdir lightning_logs/ \
            --name "Go to tensorboard" \
            --md >> report.md
        - cml-send-comment report.md

        - python dqn/dqn.py train 1 200 true
